const StatusCodes = require('./statusCodes');
const {
  ERROR_CARD_DECLINED,
  ERROR_PROCESSING_ERROR,
  ERROR_CALLER_ISSUER,
  ERROR_PICK_UP_CARD,
  ERROR_INVALID_SIGNATURE,
  ERROR_ACCOUNT_RESTRICTED,
  ERROR_ACCOUNT_INVALID,
  ERROR_PAYMENT_NOT_SUPPORTED,
  ERROR_MISSING_PARAMS,
} = require('./errorCode');

const {
  RESULT_COMPLETED,
  RESULT_FAILED,
  RESULT_VALID,
  RESULT_INVALID,
  RESULT_RESTRICTED,
} = require('./result');


const {
  TRANSACTION_TYPE_AUTHORIZATION,
  TRANSACTION_TYPE_CAPTURE,
  TRANSACTION_TYPE_REFUND,
  TRANSACTION_TYPE_VOID,
} = require('./transaction');

const {
  REFUND_TYPE_FULL,
  REFUND_TYPE_PARTIAL,
} = require('./refund');
module.exports = {
  ERROR_CARD_DECLINED,
  ERROR_PROCESSING_ERROR,
  ERROR_CALLER_ISSUER,
  ERROR_PICK_UP_CARD,
  ERROR_INVALID_SIGNATURE,
  ERROR_ACCOUNT_RESTRICTED,
  ERROR_ACCOUNT_INVALID,
  ERROR_PAYMENT_NOT_SUPPORTED,
  ERROR_MISSING_PARAMS,

  RESULT_COMPLETED,
  RESULT_FAILED,
  RESULT_VALID,
  RESULT_INVALID,
  RESULT_RESTRICTED,

  StatusCodes,

  TRANSACTION_TYPE_AUTHORIZATION,
  TRANSACTION_TYPE_CAPTURE,
  TRANSACTION_TYPE_REFUND,
  TRANSACTION_TYPE_VOID,

  REFUND_TYPE_FULL,
  REFUND_TYPE_PARTIAL,
};
